const words = 'ability': 'kabiliyet, yetenek, beceri',
    'able': 'yapabilmek, yapabilen',
    'about': 'hakkında, ilgili, konusunda',
    'above': 'yukarıda',
    'accept': 'kabul etmek',
    'according': 'göre',
    'account': 'hesap, açıklama',
    'across': 'karşısında',
    'act': 'eylem, davranış',
    'action': 'eylem, etki, hareket',
    'activity': 'faaliyet, etkinlik',
    'actually': 'aslında, gerçekte',
    'add': 'eklemek, ilave etmek',
    'address': 'adres',
    'administration': 'yönetim, idare',
    'admit': 'kabul etmek, itiraf etmek',
    'adult': 'yetişkin, erişkin',
    'affect': 'etkilemek, etki etmek',
    'after': 'sonra, ardından, daha sonra',
    'afternoon': 'öğleden sonra',
    'afterwards': 'ondan sonra',
    'again': 'tekrar, yeniden',
    'against': 'karşı',
    'age': 'yaş',
    'agency': 'ajans, acenta',
    'agent': 'ajan',
    'ago': 'önce, evvel',
    'agree': 'katılmak, hem fikir olmak',
    'agreement': 'anlaşma, sözleşme',
    'ahead': 'önde, ileri',
    'air': 'hava',
    'all': 'her şey, tüm, bütün',
    'all right': 'peki',
    'allow': 'izin vermek',
    'almost': 'neredeyse, hemen hemen',
    'alone': 'yalnız, tek başına',
    'along': 'boyunca, yanı sıra',
    'already': 'zaten',
    'also': 'ayrıca, hem de',
    'although': 'rağmen, karşın, gerçi',
    'always': 'her zaman, daima',
    'american': 'amerikan',
    'among': 'arasında, içinde',
    'amount': 'miktar, tutar',
    'analysis': 'analiz, çözümleme',
    'and': 've, ile',
    'animal': 'hayvan',
    'another': 'diğeri',
    'answer': 'cevap, yanıt',
    'any': 'herhangi, hiç, her',
    'anyone': 'kimse, herhangi biri, hiç kimse',
    'anything': 'bir şeyi herhangi bir şey, hiçbir şey',
    'anyway': 'her halükârda',
    'anywhere': 'herhangi bir yere',
    'appear': 'görünmek, gözükmek',
    'apple': 'elma',
    'apply': 'uygulamak, başvurmak',
    'approach': 'yaklaşım, yaklaşma',
    'april': 'nisan',
    'area': 'alan, bölge',
    'argue': 'tartışmak',
    'arm': 'kol',
    'around': 'etrafında',
    'arrive': 'varmak, ulaşmak',
    'art': 'sanat',
    'article': 'makale, yazı',
    'artist': 'sanatçı',
    'as': 'gibi, olarak',
    'ask': 'sormak, istemek',
    'assume': 'varsaymak, farzetmek',
    'attack': 'saldırı, atak',
    'attention': 'dikkat',
    'attorney': 'avukat, vekil',
    'audience': 'seyirci, izleyici',
    'author': 'yazar',
    'authority': 'yetki, otorite',
    'available': 'müsait',
    'avoid': 'önlemek, kaçınmak',
    'away': 'uzak, uzakta',
    'baby': 'bebek',
    'back': 'geri',
    'bad': 'kötü',
    'bag': 'sırt çantası',
    'ball': 'top',
    'bank': 'banka',
    'bar': 'bar',
    'base': 'üs, temel, baz',
    'be': 'olmak, var olmak',
    'beat': 'dövmek, yenmek',
    'beautiful': 'güzel',
    'because': 'çünkü',
    'become': 'olmak, haline gelmek',
    'bed': 'yatak',
    'before': 'önce',
    'begin': 'başlamak, başlatmak',
    'behavior': 'davranış, tutum, hareket',
    'behind': 'arkasında, gerisinde',
    'believe': 'inanmak',
    'benefit': 'yarar, fayda',
    'best': 'en iyi, en iyisi, en',
    'better': 'daha iyi, daha güzel, daha iyi şekilde',
    'between': 'arasında, aralarında',
    'beyond': 'ötesinde, öte',
    'big': 'büyük',
    'bill': 'fatura',
    'billion': 'milyar',
    'black': 'siyah',
    'blood': 'kan',
    'blue': 'mavi',
    'board': 'yazı tahtası',
    'body': 'vücut',
    'book': 'kitap',
    'born': 'doğmuş, doğum',
    'both': 'her ikisi de, ikisi de',
    'box': 'kutu',
    'boy': 'erkek çocuk',
    'break': 'kırmak',
    'bring': 'getirmek',
    'brother': 'erkek kardeş',
    'budget': 'bütçe',
    'build': 'inşa etmek',
    'building': 'bina',
    'business': 'iş',
    'but': 'fakat, ama, lakin',
    'buy': 'satın almak',
    'by': 'tarafından, ile, göre, vasıtasıyla',
    'call': 'aramak',
    'camera': 'kamera',
    'campaign': 'kampanya',
    'can': 'yapabilmek',
    'cancer': 'kanser',
    'candidate': 'aday',
    'capital': 'başkent',
    'car': 'araba',
    'card': 'kart',
    'care': 'bakım',
    'career': 'kariyer',
    'carry': 'taşımak',
    'case': 'dava',
    'catch': 'yakalamak',
    'cause': 'sebep olmak',
    'cell': 'hücre',
    'center': 'merkez',
    'central': 'merkezi',
    'century': 'yüzyıl',
    'certain': 'belirli, kesin',
    'certainly': 'kesinlikle',
    'chair': 'sandalye',
    'challenge': 'meydan okuma',
    'chance': 'şans',
    'change': 'değişiklik',
    'character': 'karakter',
    'charge': 'şarj etmek',
    'check': 'kontrol etmek, denetlemek',
    'child': 'çocuk',
    'choice': 'seçim, seçenek',
    'choose': 'seçmek',
    'church': 'kilise',
    'citizen': 'vatandaş',
    'city': 'şehir',
    'civil': 'sivil',
    'claim': 'iddia etmek, iddia',
    'class': 'sınıf',
    'clear': 'temiz, açık',
    'clearly': 'açıkça',
    'close': 'kapatmak',
    'coach': 'koç',
    'cold': 'soğuk',
    'collection': 'toplamak',
    'college': 'kolej',
    'color': 'renk',
    'come': 'gelmek',
    'commercial': 'ticari',
    'common': 'ortak',
    'community': 'topluluk',
    'company': 'şirket',
    'compare': 'karşılaştırmak',
    'computer': 'bilgisayar',
    'concern': 'ilişkisi olmak, ait olmak, ilgilendirmek',
    'condition': 'şart',
    'conference': 'konferans',
    'congress': 'kongre',
    'consider': 'dikkate almak',
    'consumer': 'tüketici',
    'contain': 'içermek',
    'continue': 'devam etmek',
    'control': 'kontrol',
    'cost': 'maliyet',
    'country': 'ülke',
    'couple': 'çift',
    'course': 'ders',
    'court': 'mahkeme',
    'cover': 'örtmek',
    'create': 'yaratmak',
    'crime': 'suç',
    'cultural': 'kültürel',
    'culture': 'kültür',
    'cup': 'fincan',
    'current': 'şu andaki',
    'customer': 'müşteri',
    'data': 'veri',
    'date': 'tarih',
    'day': 'gün',
    'decide': 'karar vermek',
    'decision': 'karar',
    'deep': 'derin',
    'defense': 'savunma',
    'define': 'tanımlamak',
    'degree': 'derece',
    'demonstrate': 'göstermek, sergilemek',
    'design': 'tasarım',
    'detail': 'detay',
    'determine': 'belirlemek',
    'develop': 'gelişmek',
    'development': 'gelişim',
    'different': 'farklı',
    'difficult': 'zor',
    'dinner': 'akşam yemeği',
    'direct': 'doğrudan',
    'direction': 'yön',
    'discover': 'keşfetmek',
    'discuss': 'tartışmak',
    'discussion': 'tartışma',
    'doctor': 'doktor',
    'door': 'kapı',
    'down': 'aşağı',
    'during': 'sırasında',
    'each': 'her',
    'early': 'erken',
    'east': 'doğu',
    'easy': 'kolay',
    'economic': 'ekonomik',
    'education': 'eğitim',
    'effect': 'etki',
    'effort': 'çaba',
    'eight': 'sekiz',
    'either': 'ya da',
    'election': 'seçim',
    'else': 'başka',
    'end': 'son',
    'energy': 'enerji',
    'engage': 'katılmak',
    'enjoy': 'keyif almak',
    'enough': 'yeterli',
    'enter': 'girmek',
    'environment': 'çevre',
    'especially': 'özellikle',
    'estimate': 'tahmin',
    'even': 'hatta, bile',
    'event': 'etkinlik, olay',
    'ever': 'hiç',
    'every': 'her',
    'everybody': 'herkes',
    'everyone': 'herkes',
    'everything': 'her şey',
    'evidence': 'kanıt',
    'exact': 'tam, kesin',
    'example': 'örnek',
    'experience': 'deneyim',
    'expert': 'uzman',
    'explain': 'açıklamak',
    'face': 'yüz, yüzleşmek',
    'fact': 'gerçek',
    'family': 'aile',
    'famous': 'meşhur',
    'far': 'uzak',
    'fast': 'hızlı',
    'father': 'baba',
    'fear': 'korku',
    'feel': 'hissetmek',
    'few': 'az',
    'field': 'alan, saha',
    'fight': 'savaşmak, kavga etmek',
    'find': 'bulmak',
    'fine': 'iyi',
    'finish': 'bitirmek',
    'first': 'ilk',
    'five': 'beş',
    'follow': 'takip etmek',
    'for': 'için',
    'forget': 'unutmak',
    'form': 'biçim',
    'former': 'eski, önceki',
    'four': 'dört',
    'free': 'ücretsiz',
    'friend': 'dost',
    'from': 'den',
    'front': 'ön',
    'full': 'dolu',
    'fun': 'eğlence',
    'future': 'gelecek',
    'game': 'oyun',
    'garden': 'bahçe',
    'general': 'genel',
    'get': 'almak',
    'give': 'vermek',
    'glass': 'şişe, cam',
    'go': 'gitmek',
    'good': 'iyi',
    'government': 'hükümet',
    'great': 'büyük',
    'green': 'yeşil',
    'ground': 'zemin',
    'group': 'grup',
    'grow': 'büyümek',
    'growth': 'büyüme',
    'guarantee': 'garanti',
    'guess': 'tahmin etmek',
    'handle': 'tutmak, yönetmek',
    'happen': 'olmak',
    'happy': 'çok mutlu',
    'hard': 'sert, zor',
    'has': 'var',
    'have': 'sahip olmak, olmak',
    'he': 'o',
    'head': 'kafa',
    'health': 'sağlık',
    'hear': 'duymak',
    'heart': 'kalp',
    'help': 'yardım etmek',
    'here': 'burada',
    'high': 'yüksek',
    'him': 'o',
    'his': 'onun',
    'history': 'tarih',
    'hold': 'tutmak',
    'home': 'ev',
    'hope': 'umut etmek',
    'hospital': 'hastane',
    'hot': 'sıcak',
    'hotel': 'otel',
    'house': 'ev',
    'how': 'nasıl',
    'human': 'insan',
    'hundred': 'yüz',
    'husband': 'koca',
    'i': 'ben',
    'if': 'eğer',
    'impact': 'etki',
    'important': 'önemli',
    'include': 'içermek',
    'increase': 'arttırmak',
    'interest': 'ilgi',
    'international': 'uluslararası',
    'issue': 'konu',
    'it': 'o',
    'item': 'madde',
    'its': 'onun',
    'job': 'iş',
    'join': 'katılmak',
    'just': 'sadece',
    'keep': 'saklamak',
    'kind': 'tür',
    'know': 'bilmek',
    'language': 'dil',
    'large': 'büyük',
    'last': 'son',
    'late': 'geç',
    'leave': 'bırakmak',
    'left': 'sol',
    'less': 'daha az',
    'let': 'izin vermek',
    'life': 'yaşam',
    'like': 'sevgi',
    'line': 'çizgi',
    'little': 'küçük',
    'live': 'yaşamak',
    'long': 'uzun',
    'look': 'görmek',
    'make': 'yapmak',
    'man': 'adam',
    'many': 'birçok',
    'market': 'pazar',
    'may': 'olabilir',
    'me': 'beni',
    'mean': 'anlamına gelmek',
    'medical': 'tıbbi',
    'meet': 'tanışmak',
    'might': 'olabilir',
    'more': 'daha fazla',
    'most': 'en çok',
    'mother': 'anne',
    'move': 'hareket',
    'much': 'çok',
    'music': 'müzik',
    'name': 'isim',
    'need': 'ihtiyaç duymak',
    'new': 'yeni',
    'next': 'sonraki',
    'no': 'hayır',
    'not': 'değil',
    'nothing': 'hiçbir şey',
    'now': 'şimdi',
    'number': 'sayı',
    'object': 'isim',
    'off': 'kapalı',
    'offer': 'teklif',
    'often': 'sıklıkla',
    'oh': 'ah',
    'ok': 'tamam',
    'old': 'eski',
    'on': 'üzerinde',
    'one': 'bir',
    'only': 'sadece',
    'open': 'açık',
    'option': 'seçenek',
    'order': 'sipariş',
    'other': 'diğer',
    'our': 'bizim',
    'out': 'dışarı',
    'over': 'üzerinde',
    'own': 'sahip olmak',
    'page': 'sayfa',
    'part': 'parça',
    'past': 'geçmiş',
    'pay': 'ödeme',
    'people': 'insanlar',
    'place': 'yer',
    'plan': 'plan',
    'play': 'oynamak',
    'point': 'nokta',
    'political': 'siyasi',
    'poor': 'fakir',
    'possible': 'mümkün',
    'power': 'güç',
    'present': 'mevcut',
    'president': 'başkan',
    'press': 'baskı',
    'pretty': 'güzel',
    'provide': 'sunmak',
    'public': 'kamusal',
    'purpose': 'amaç',
    'question': 'soru',
    'quick': 'hızlı',
    'quiet': 'sessiz',
    'quite': 'oldukça',
    'rate': 'oran',
    'read': 'okumak',
    'real': 'gerçek',
    'recent': 'son zamanlarda',
    'right': 'doğru',
    'room': 'oda',
    'run': 'koşmak',
    'safe': 'güvenli',
    'same': 'aynı',
    'say': 'söylemek',
    'school': 'okul',
    'second': 'ikinci',
    'see': 'görmek',
    'sell': 'satmak',
    'send': 'göndermek',
    'sense': 'hissetmek',
    'service': 'hizmet',
    'set': 'set, kurmak',
    'show': 'göstermek',
    'side': 'yan',
    'sign': 'işaret',
    'simple': 'basit',
    'since': 'den beri',
    'social': 'sosyal',
    'some': 'bazı',
    'soon': 'yakında',
    'space': 'alan',
    'special': 'özel',
    'speak': 'konuşmak',
    'spend': 'harcamak',
    'stand': 'durmak',
    'start': 'başlamak',
    'state': 'durum',
    'still': 'hala',
    'store': 'mağaza',
    'student': 'öğrenci',
    'study': 'çalışmak',
    'such': 'böyle',
    'system': 'sistem',
    'take': 'almak',
    'talk': 'konuşmak',
    'team': 'takım',
    'tell': 'söylemek',
    'term': 'terim',
    'test': 'test',
    'than': 'daha',
    'that': 'o',
    'the': 'belirli artikel',
    'their': 'onların',
    'them': 'onlara',
    'then': 'sonra',
    'there': 'orada',
    'these': 'bunlar',
    'they': 'onlar',
    'thing': 'şey',
    'this': 'bu',
    'those': 'şunlar',
    'through': 'içinden',
    'time': 'zaman',
    'to': 'e',
    'today': 'bugün',
    'together': 'birlikte',
    'too': 'çok',
    'under': 'altında',
    'understand': 'anlamak',
    'until': 'kadar',
    'up': 'yukarı',
    'use': 'kullanmak',
    'very': 'çok',
    'victim': 'kurban',
    'view': 'görüş',
    'vote': 'oy vermek',
    'way': 'yol',
    'we': 'biz',
    'well': 'iyi',
    'what': 'ne',
    'when': 'ne zaman',
    'where': 'nerede',
    'which': 'hangi',
    'who': 'kim',
    'whom': 'kimi',
    'why': 'neden',
    'will': 'will',
    'with': 'ile',
    'work': 'çalışmak',
    'world': 'dünya',
    'would': 'would',
    'year': 'yıl',
    'yes': 'evet',
    'you': 'sen',
    'your': 'senin',
    'zoo': 'hayvanat bahçesi'
};

let currentWord;
let score = 0;

function getRandomWord() {
    const wordKeys = Object.keys(words);
    currentWord = wordKeys[Math.floor(Math.random() * wordKeys.length)];
    document.getElementById('word').innerText = currentWord;
}

function setupOptions() {
    const optionsContainer = document.getElementById('options');
    optionsContainer.innerHTML = ''; // Temizle

    const correctAnswer = words[currentWord];
    const wrongAnswers = Object.values(words).filter(word => word !== correctAnswer);
    const options = [correctAnswer, ...wrongAnswers.sort(() => 0.5 - Math.random()).slice(0, 3)];
    options.sort(() => 0.5 - Math.random());

    options.forEach(option => {
        const button = document.createElement('button');
        button.innerText = option;
        button.onclick = () => checkAnswer(option);
        optionsContainer.appendChild(button);
    });
}

function checkAnswer(selectedOption) {
    const correctAnswer = words[currentWord];
    if (selectedOption === correctAnswer) {
        score += 10;
        alert('Doğru!');
    } else {
        alert('Yanlış! Doğru cevap: ' + correctAnswer);
    }
    document.getElementById('score').innerText = 'Puan: ' + score;
    getRandomWord();
    setupOptions();
}

document.getElementById('pronounce').onclick = function() {
    const utterance = new SpeechSynthesisUtterance(currentWord);
    window.speechSynthesis.speak(utterance);
};

// Sayfa yüklendiğinde ilk kelimeyi al
window.onload = () => {
    getRandomWord();
    setupOptions();
};
